### PR TITLE
Reduced threshold for composite name shortening (RT#106276)

### PR DESCRIPTION
**Pull request by pjfl**

### CODE REVIEW

**Comment by haarg** [comment]
The test doesn't seem to be passing.

**Comment by pjfl** [comment]
Shaved the test down so that it has no additional dependencies

**Comment by karenetheridge** [comment]
cool, the test passes now!

FWIW, you can simplify the `$@` checking with Test::Fatal (which is used elsewhere in the test suite):
`is(exception { $class->new }, undef, 'package name usable by perl');`

**Comment by wchristian** [comment]
Those commits could stand being combined. No need to have "oops" commits around. :)

**Comment by karenetheridge** [comment]
Exactly -- https://speakerdeck.com/sartak/right-the-first-time

**Comment by haarg** [comment]
Just shortening the max length won't resolve some other issues relating to long names.  I have a fix for this on the Moo side instead: https://github.com/moose/Moo/commit/ad4ca68ebd42a75ff73b0f32f8969fbbc380c771

**Pull request closed without merging**
